fannie = read.table("acqSubset.csv",header=TRUE,sep=",")
View(fannie)
range(fannie$orgDebttoIncomeRatio,na.rm = TRUE)
mean(fannie$orgDebttoIncomeRatio,na.rm=TRUE)
sd(fannie$orgDebttoIncomeRatio,na.rm=TRUE)
range(fannie$borrowerCreditScoreAtOrigination,na.rm = TRUE)
mean(fannie$borrowerCreditScoreAtOrigination,na.rm = TRUE)
sd(fannie$borrowerCreditScoreAtOrigination,na.rm = TRUE)
extr = data.frame(fannie$zipCodeShort,fannie$numBorrowers,fannie$orgDebttoIncomeRatio,fannie$borrowerCreditScoreAtOrigination)
extr$average <- 0
str <- c("zipCode","numBorrowers","debtToIncomeRatio","creditScore","average")
colnames(extr) = str
View(extr)
extr$average <-  extr$average
extr$average <- ifelse(extr$numBorrowers==2,2,0)
extr$average <- ifelse(extr$numBorrowers==3,4,extr$average)
extr$average <- ifelse(extr$numBorrowers==4,5,extr$average)
extr$average <- ifelse(extr$numBorrowers==5,5,extr$average)
extr$average <- ifelse(extr$numBorrowers==6,5,extr$average)
extr$average <- ifelse(extr$numBorrowers==7,5,extr$average)
extr$average <- ifelse(extr$numBorrowers==8,5,extr$average)
extr$average <- ifelse(extr$numBorrowers==9,5,extr$average)
extr$average <- ifelse(extr$numBorrowers==10,5,extr$average)
extr$average <- ifelse(extr$debtToIncomeRatio>=13,extr$average+1,extr$average)
extr$average <- ifelse(extr$debtToIncomeRatio>=23,extr$average+1,extr$average)
extr$average <- ifelse(extr$debtToIncomeRatio>=33,extr$average+1,extr$average)
extr$average <- ifelse(extr$debtToIncomeRatio>=43,extr$average+1,extr$average)
extr$average <- ifelse(extr$debtToIncomeRatio>=53,extr$average+1,extr$average)
extr$average <- ifelse(extr$creditScore<=800,extr$average+1,extr$average)
extr$average <- ifelse(extr$creditScore<=750,extr$average+1,extr$average)
extr$average <- ifelse(extr$creditScore<=700,extr$average+1,extr$average)
extr$average <- ifelse(extr$creditScore<=650,extr$average+1,extr$average)
extr$average <- ifelse(extr$creditScore<=600,extr$average+1,extr$average)
extr$average <- ifelse(extr$creditScore<=550,extr$average+1,extr$average)
extr$average <- ifelse(extr$creditScore<=500,extr$average+1,extr$average)
extr$average <- ifelse(extr$creditScore<=450,extr$average+1,extr$average)
extr$average <- ifelse(extr$creditScore<=400,extr$average+1,extr$average)
extr$average <- ifelse(extr$creditScore<=350,extr$average+1,extr$average)
range(extr$average,na.rm = TRUE)
extr$average <- extr$average*5/17
nr <- na.omit(extr)
final <- data.frame("zipCode"=100:999,"average"=0)
for (year in 100:999){View(final) final[final$zipCode==year,][1,2] = sum(nr[nr$zipCode==year,]$average)/length(nr[nr$zipCode==year,][,1])}
plot(average~zipCode,data=final,pch=20)
write.csv(final,"final.csv")
